# Configuration for Ruby CI
# To force the execution of this workflow, add [run ruby] to your commit message
name: 'CI - Ruby'

on:
  push:

jobs:
  build:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ 'selenium-devtools', 'selenium-webdriver' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: truffleruby-head
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-ruby-build-gem-${{ matrix.target }}-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-ruby-build-gem-${{ matrix.target }}-
      - uses: ./.github/actions/setup-bazelisk
      - uses: ./.github/actions/bazel
        with:
          command: build //rb:${{ matrix.target }}

  firefox-test:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ 'firefox-test', 'remote-firefox-test' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: truffleruby-head
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-ruby-${{ matrix.target }}-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-ruby-${{ matrix.target }}-
      - uses: ./.github/actions/setup-bazelisk
      - name: Setup Fluxbox
        run: sudo apt-get -y install fluxbox
      - name: Setup Firefox and GeckoDriver
        uses: ./.github/actions/setup-firefox
      - run: Xvfb :99 &
      - name: Start Fluxbox
        run: fluxbox -display :99 &
      - uses: ./.github/actions/bazel
        with:
          command: test --test_output=all //rb:${{ matrix.target }}
        env:
          DISPLAY: :99

  unit-test:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', 'truffleruby-head' ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-ruby-unit-test-${{ matrix.ruby }}-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-ruby-unit-test-${{ matrix.ruby }}-
      - uses: ./.github/actions/setup-bazelisk
      - uses: ./.github/actions/bazel
        with:
          command: test --test_output=all //rb:unit-test
